language: php

php:
  - 5.3
  - 5.4

before_script: 
    - sudo apt-get update -y
    - sudo apt-get install -y php-pear
    #- sudo apt-get install -y php5-dev
    #- pecl install mongo
    - git submodule update --init

script: phpunit -c app/phpunit.xml.dist
